<?php 
if (defined('RUNNING_FROM_ROOT')) {
  //$this->plugin('basePath')->setBasePath($this->basePath().'/public');
    
    $auth = new Zend\Authentication\AuthenticationService();
//    echo '<pre>';print_r($auth->getIdentity());exit;
//    
//    if($auth->hasIdentity())
//        $this->loggedInUserDetails = $auth->getIdentity(); 
    
    $roleInSession = new Zend\Session\Container('roleInSession');
    $roleRightsArr  = $roleInSession->roleRightsArr; 
} ?>

<?php $baseUrl = $this->basePath(); ?>

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CRM | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/dist/css/skins/_all-skins.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/plugins/iCheck/flat/blue.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/plugins/morris/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/plugins/datepicker/datepicker3.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/plugins/daterangepicker/daterangepicker-bs3.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
    
    <!----customize-CSS------->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/dist/css/customize.css">
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <style>
        .mandatory{
            color :#FF0000;
        }
    </style>
    
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

      <header class="main-header">
        <!-- Logo -->
        <a href="index2.html" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><img src="<?php echo $baseUrl;?>/public/dist/img/discovery-logo-sm.png"></span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><img src="<?php echo $baseUrl;?>/public/dist/img/discovery-logo.png"></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              <li class="dropdown messages-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-envelope-o"></i>
                  <span class="label label-success">4</span>                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 4 messages</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li><!-- start message -->
                        <a href="#">
                          <div class="pull-left">
                            <img src="<?php echo $baseUrl;?>/public/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                          </div>
                          <h4>
                            Message First
                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                          </h4>
                          <p>Lorem Ipsum is simply dummy text</p>
                        </a>
                      </li><!-- end message -->
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="<?php echo $baseUrl;?>/public/dist/img/user3-128x128.jpg" class="img-circle" alt="User Image">
                          </div>
                          <h4>
                            Message Second
                            <small><i class="fa fa-clock-o"></i> 2 hours</small>
                          </h4>
                          <p>Lorem Ipsum is simply dummy text</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="<?php echo $baseUrl;?>/public/dist/img/user4-128x128.jpg" class="img-circle" alt="User Image">
                          </div>
                          <h4>
                            Message Third
                            <small><i class="fa fa-clock-o"></i> Today</small>
                          </h4>
                          <p>Lorem Ipsum is simply dummy text</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="<?php echo $baseUrl;?>/public/dist/img/user3-128x128.jpg" class="img-circle" alt="User Image">
                          </div>
                          <h4>
                            Message Fourth
                            <small><i class="fa fa-clock-o"></i> Yesterday</small>
                          </h4>
                          <p>Lorem Ipsum is simply dummy text</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="<?php echo $baseUrl;?>/public/dist/img/user4-128x128.jpg" class="img-circle" alt="User Image">
                          </div>
                          <h4>
                            Message Fifth
                            <small><i class="fa fa-clock-o"></i> 2 days</small>
                          </h4>
                          <p>Lorem Ipsum is simply dummy text</p>
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">See All Messages</a></li>
                </ul>
              </li>
              <!-- Notifications: style can be found in dropdown.less -->
              <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-bell-o"></i>
                  <span class="label label-warning">10</span>                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 10 notifications</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-aqua"></i> 5 new members joined today
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the page and may cause design problems
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-red"></i> 5 new members joined
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-user text-red"></i> You changed your username
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">View all</a></li>
                </ul>
              </li>             
              
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="<?php echo $baseUrl;?>/public/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
                  <span class="hidden-xs"><?php echo $auth->getIdentity()->username;?></span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <img src="<?php echo $baseUrl;?>/public/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                    <p>
                      <?php echo $auth->getIdentity()->username;?> (<?php echo $roleRightsArr['role_name'];?>)
                      <small>Member since <?php $dateArr = explode(' ',$auth->getIdentity()->date_created);echo $dateArr[0];?></small>
                    </p>
                  </li>
                  <!-- Menu Body -->
                  
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="#" class="btn btn-default btn-flat">Profile</a>
                    </div>
                    <div class="pull-right">
                      <a href="<?php echo $baseUrl;?>/index/logout" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
              <!-- Control Sidebar Toggle Button -->              
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="<?php echo $baseUrl;?>/public/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
              <p><?php echo $auth->getIdentity()->username;?></p>
              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>
          <!-- search form -->
          <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
          <!-- /.search form -->
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            <li class="active treeview">
              <?php if($roleRightsArr['seniority'] == 1){?>
              <a href="<?php echo $baseUrl;?>/admin/dashboard"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a> 
              <?php }else{?>
              <a href="<?php echo $baseUrl;?>/admin/userdashboard"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a> 
              <?php }?>
            </li> 
            
            <?php if($roleRightsArr['seniority'] == 1 || $roleRightsArr['seniority'] == 2){?>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-pie-chart"></i>
                <span>Users</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="<?php echo $baseUrl;?>/admin/manageusers"><i class="fa fa-circle-o"></i> Manage Users</a></li>  
                <li><a href="<?php echo $baseUrl;?>/admin/addedituser"><i class="fa fa-circle-o"></i> Add User</a></li>            
              </ul>
            </li>  
            <li class="treeview">
              <a href="<?php echo $baseUrl;?>/admin/manageroles"><i class="fa fa-dashboard"></i> <span>Manage Roles</span></a>              
            </li>
            <?php } ?>
            
    <!--    <li class="treeview">
              <a href="#">
                <i class="fa fa-pie-chart"></i>
                <span>Roles</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="<?php echo $baseUrl;?>/admin/manageroles"><i class="fa fa-circle-o"></i> Manage Roles</a></li>  
                <li><a href="<?php echo $baseUrl;?>/admin/addeditrole"><i class="fa fa-circle-o"></i> Add Role</a></li>           
              </ul>
            </li>  
    -->         
            
            
            <li class="treeview">
              <a href="#">
                <i class="fa fa-pie-chart"></i>
                <span>Leads</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <?php if(in_array(1, $roleRightsArr['rightsArr'])){?>
                <li><a href="<?php echo $baseUrl;?>/admin/addeditleads"><i class="fa fa-circle-o"></i> Add Leads</a></li>
                <?php } if (in_array(2, $roleRightsArr['rightsArr'])){?>
                <li><a href="<?php echo $baseUrl;?>/admin/manageleads"><i class="fa fa-circle-o"></i> View Leads</a></li>
                <li><a href="<?php echo $baseUrl;?>/admin/assignedleads"><i class="fa fa-circle-o"></i> Assigned Leads</a></li>                          <?php } ?>
              </ul>
            </li> 
             <?php if($roleRightsArr['seniority'] == 1 || $roleRightsArr['seniority'] == 2){?>
            <li class="treeview">
              <a href="<?php echo $baseUrl;?>/admin/projects"><i class="fa fa-dashboard"></i> <span>Manage Projects</span></a>               </li>
            <li class="treeview">
              <a href="<?php echo $baseUrl;?>/admin/sources"><i class="fa fa-dashboard"></i> <span>Manage Sources</span></a>                </li>
             <?php }?>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

	  
	  <?php echo $this->layout()->content; ?>
	  
	  
	  
	  
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          
        </div>
        <strong>Copyright &copy; 2014-2015 <a href="http://www.discoverysolutions.in/" target="_blank">Discovery Solutions</a>.</strong> All rights reserved.
      </footer>

    </div><!-- ./wrapper -->

    <!-- jQuery 2.1.4 -->
    <script src="<?php echo $baseUrl;?>/public/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.5 -->
    <script src="<?php echo $baseUrl;?>/public/bootstrap/js/bootstrap.min.js"></script>
    
    
   
    
    
    <!-- Morris.js charts 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="<?php echo $baseUrl;?>/public/plugins/morris/morris.min.js"></script>-->
    <!-- Sparkline 
    <script src="<?php echo $baseUrl;?>/public/plugins/sparkline/jquery.sparkline.min.js"></script>-->
    <!-- jvectormap 
    <script src="<?php echo $baseUrl;?>/public/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="<?php echo $baseUrl;?>/public/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>-->
    <!-- jQuery Knob Chart 
    <script src="<?php echo $baseUrl;?>/public/plugins/knob/jquery.knob.js"></script>-->
    <!-- daterangepicker 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
    <script src="<?php echo $baseUrl;?>/public/plugins/daterangepicker/daterangepicker.js"></script>-->
    <!-- datepicker 
    <script src="<?php echo $baseUrl;?>/public/plugins/datepicker/bootstrap-datepicker.js"></script>-->
    <!-- Bootstrap WYSIHTML5 
    <script src="<?php echo $baseUrl;?>/public/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>-->
    <!-- Slimscroll 
    <script src="<?php echo $baseUrl;?>/public/plugins/slimScroll/jquery.slimscroll.min.js"></script>-->
    <!-- FastClick 
    <script src="<?php echo $baseUrl;?>/public/plugins/fastclick/fastclick.min.js"></script>-->
    <!-- AdminLTE App -->
    <script src="<?php echo $baseUrl;?>/public/dist/js/app.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) 
    <script src="<?php echo $baseUrl;?>/public/dist/js/pages/dashboard.js"></script>-->
    <!-- AdminLTE for demo purposes 
    <script src="<?php echo $baseUrl;?>/public/dist/js/demo.js"></script>-->
    
  </body>
</html>
