<?php $baseUrl = $this->basePath(); ?>
<!-- Content Wrapper. Contains page content -->
    <!-- Angular js file -->
   <style>
    [ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {
      display: none !important;
    }
  </style>
  
    
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Roles
            <small>(Add/Edit Role)</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Roles</li>
            <li class="active">Add New Role</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Small boxes (Stat box) -->
          <!-- /.row -->
          <!-- Main row -->
          <div class="row">
            <!-- Left col -->
            <section class="col-lg-12 connectedSortable">
              <!-- Add user form-->
              <div class="box box-primary box-custom">
                <div class="box-header with-border">
                  <h3 class="box-title">Basic Information</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <div class="container">
                    <div class="col-lg-11"  style="background-color:#fff; margin-top:60px; margin-bottom:60px;">
                        <form  action="#" method="post" ng-controller="validateCtrl" name="myForm" novalidate>
                            <input type="hidden" name="roleId" ng-model="roleId">
                            <div class="form-group-custom">
                                <label>Role Name</label>
                                <input type="text" name="roleName" class="form-control" placeholder="Role Name" ng-model="roleName"  required>
                                <span style="color:red;" ng-cloak ng-show="(myForm.roleName.$dirty && myForm.roleName.$invalid)">
                                <span ng-show="myForm.roleName.$error.required">Role Name is required.</span>
                                </span>
                            </div>
                            <div class="form-group-custom">
                                <label>Select Rights</label>
                                <div class="row">
                                    <div class="col-md-2" ng-repeat="role in allRoles">
                                    <input id="{{role.name}}" name="roleRights[]" type="checkbox" value="{{role.id}}" ng-checked="selection.indexOf(role.id) > -1" ng-click="toggleSelection(role.id)" />
                                    <label for="{{role.name}}"></label>
                                 {{role.name}}
                               </div>
                                </div>
                                <span id="rightsCheckbox" style="display:none;color:red;">Rights is required.</span>
                            </div> 
                          <div class="box-footer-custom">
                            <button class="btn btn-primary" type="submit" ng-disabled="(myForm.$invalid || selection.length == 0)">Save</button>
                            <button class="btn btn-danger" type="button" style="margin-left:10px;" ng-click="cancelBtn()">Cancel</button>
                          </div>
                        </form>
                    </div>
                </div>
              </div>
              <!-- /End of Add user form -->

             <!-- Add new Graph ----------------------------------------------------><!-- /.box -->             

            </section><!-- /.Left col -->            
          </div><!-- /.row (main row) -->

        </section><!-- /.content -->
      </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
   <script src="<?php echo $baseUrl;?>/public/angular.min.js"></script>
  <script>
    var app = angular.module('myApp', []);
    var roleArr         = <?php if(isset($this->roleArr)) echo $this->roleArr; else echo '{}'?>;
    var roleRightsArr   = <?php if(isset($this->roleRightsArr)) echo $this->roleRightsArr; else echo '{}'?>;
    app.controller('validateCtrl', function($scope) {
        $scope.allRoles=[
            {name:'Punching', id:1},
            {name:'Assign Lead', id:2},
            {name:'Update Lead Status', id:3},
            {name:'Delete Lead', id:4},
            {name:'Download Data', id:5}
        ];
        
        if(Object.keys(roleArr).length > 0){
            $scope.roleName = roleArr.role_name;
            $scope.roleId   = roleArr.id;
        }
       $scope.selection=[];
       
       if(Object.keys(roleRightsArr).length >0){
            angular.forEach(roleRightsArr, function(value, key){
               $scope.selection.push(parseInt(value));
            });
       }
       
       $scope.toggleSelection = function toggleSelection(roleId) {
          var idx = $scope.selection.indexOf(roleId);
          if (idx > -1) {
            $scope.selection.splice(idx, 1);
          } else {
            $scope.selection.push(roleId);
          }
          
          if($scope.selection.length==0) 
            $('#rightsCheckbox').show();
          else
            $('#rightsCheckbox').hide(); 
        };
         
        $scope.cancelBtn = function(){
            window.location.href = '<?php echo $baseUrl?>/admin/manageroles';
        }
    });
    
    // ng-app was ommitted from the html so that
    // we can manually bootstray (initialize)
    // angular after a delay to simulate the 
    // actual code being loaded later
    setTimeout(function(){
      angular.element(document).ready(function() {
          //console.log('document Ready');
        angular.bootstrap(document, ['myApp']);
      });  
    },1000);
</script>