<?php $baseUrl = $this->basePath(); 

//echo '<pre>';
//print_r($this->magicBrickDetail);
//print_r($this->acresData);
//print_r($this->smsApiData);
//exit;

?>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        API Credentials
        <small>&nbsp;</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <!---<li>&nbsp;</li>--->
        <li class="active">API Credential</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <form> 
            <div class="box-header">
              <h3 class="box-title">Magic Bricks <small>&nbsp;</small></h3>                  
            </div><!-- /.box-header -->
            <div class="box-body pad">
                <input type="hidden" value="<?php if(count($this->magicBrickDetail)) echo $this->magicBrickDetail[0]['id']?>" id="MagicBricksId">
               <div class="col-md-3 col-sm-6 col-xs-6 show-interested">
                    <div class="form-group">
                        <label>Magic Bricks Source</label>
                        <input class="form-control" type="text" id="MagicBricksSource" value="<?php if(count($this->magicBrickDetail)) echo $this->magicBrickDetail[0]['source_id']?>">
                        <span id="MagicBricksSourceErr" style="display:none;color:red">Magic Bricks Source is required.</span>
                        </div><!-- /.form-group -->                      
                </div><!-- ./col -->
                <div class="col-md-3 col-sm-6 col-xs-6 show-not-interested">
                  <div class="form-group">
                        <label>Magic Bricks Key</label>
                        <input class="form-control" type="text" id="MagicBricksKey" value="<?php if(count($this->magicBrickDetail)) echo $this->magicBrickDetail[0]['magic_brick_key']?>">
                        <span id="MagicBricksKeyErr" style="display:none;color:red">Magic Bricks Key is required.</span>
                        </div><!-- /.form-group -->                  
                </div><!-- ./col -->

            </div>
            <div class="box-footer-customize pad-left-3">
                <button class="btn btn-primary" type="button" id="MagicBricksBtn" disabled="disabled" onclick="magicBricksForm()">Save</button>                  
            </div>
            </form>
          </div><!-- /.box -->

          <div class="box marg-top-3">
               <form>
            <div class="box-header">
              <h3 class="box-title">99 Acres <small>&nbsp;</small></h3>                 
            </div><!-- /.box-header -->
            <div class="box-body pad">
        <input type="hidden" id="AcresId" value="<?php if(count($this->acresData)) echo $this->acresData[0]['id']?>">
               <div class="col-md-3 col-sm-6 col-xs-6 show-interested">
                    <div class="form-group">
                        <label>99 Acres Source</label>
                        <input class="form-control" type="text" id="AcresSource" value="<?php if(count($this->acresData)) echo $this->acresData[0]['source_id']?>">
                        <span id="AcresSourceErr" style="display:none;color:red">99 Acres Source is required.</span>
                        </div><!-- /.form-group -->                      
                </div><!-- ./col -->
                <div class="col-md-3 col-sm-6 col-xs-6 show-not-interested">
                  <div class="form-group">
                        <label>User Name</label>
                        <input class="form-control" type="text" id="AcresUserName" value="<?php if(count($this->acresData)) echo $this->acresData[0]['acres_username']?>">
                        <span id="AcresUserNameErr" style="display:none;color:red">User Name is required.</span>
                        </div><!-- /.form-group -->                  
                </div><!-- ./col -->
                <div class="col-md-3 col-sm-6 col-xs-6 show-not-interested">
                  <div class="form-group">
                        <label>Password</label>
                        <input class="form-control" type="text" id="AcresUserPswd" value="<?php if(count($this->acresData)) echo $this->acresData[0]['acres_pswd']?>">
                        <span id="AcresUserPswdErr" style="display:none;color:red">Password is required.</span>
                        </div><!-- /.form-group -->                  
                </div><!-- ./col -->

            </div>
            <div class="box-footer-customize pad-left-3">
                <button class="btn btn-primary" type="button" disabled="disabled" id="AcresBtn" onclick="acresForm()">Save</button>                   
            </div>
            </form>
          </div>

          <div class="box marg-top-3">
            <form>
            <div class="box-header">
              <h3 class="box-title">sms <small>&nbsp;</small></h3>                 
            </div><!-- /.box-header -->
            <div class="box-body pad">
                <input type="hidden" value="<?php if(count($this->smsApiData)) echo $this->smsApiData[0]['id']?>" id="smsApiId">
                <div class="col-md-3 col-sm-6 col-xs-6 show-not-interested">
                  <div class="form-group">
                        <label>User Name</label>
                        <input class="form-control" type="text" id="smsApiUsrName" value="<?php if(count($this->smsApiData)) echo $this->smsApiData[0]['sms_user_name']?>">
                        <span id="smsApiUsrNameErr" style="display:none;color:red">User Name is required.</span>
                        </div><!-- /.form-group -->                  
                </div><!-- ./col -->
                <div class="col-md-3 col-sm-6 col-xs-6 show-not-interested">
                  <div class="form-group">
                        <label>Password</label>
                        <input class="form-control" type="text"  id="smsApiUsrPswd" value="<?php if(count($this->smsApiData)) echo $this->smsApiData[0]['sms_pswd']?>">
                        <span id="smsApiUsrPswdErr" style="display:none;color:red">Password is required.</span>
                        </div><!-- /.form-group -->                  
                </div><!-- ./col -->

            </div>
            <div class="box-footer-customize pad-left-3">
                <button class="btn btn-primary" type="button" disabled="disabled" id="smsApiBtn" onclick="smsApiForm()"> Save</button>              
            </div>
            </form>
          </div>

        </div><!-- /.col-->
      </div><!-- ./row -->
    </section><!-- /.content -->
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script>
    magicBrickBtn();
    acresBtn();
    smsApiBtn();
    // Magic brick Form validations
    
    $('#MagicBricksSource').blur(function(){
        if($('#MagicBricksSource').val() == ''){
            $('#MagicBricksBtn').attr('disabled','disabled');
            $("#MagicBricksSourceErr").show();
        }else{
            $("#MagicBricksSourceErr").hide();
        }
        magicBrickBtn();
    });
    $('#MagicBricksKey').blur(function(){
         if($('#MagicBricksKey').val() == ''){
            $('#MagicBricksBtn').attr('disabled','disabled');
            $("#MagicBricksKeyErr").show();
        }else{
            $("#MagicBricksKeyErr").hide();
        }
        magicBrickBtn();
    });
    
    function magicBrickBtn(){
        if($('#MagicBricksSource').val()!='' && $('#MagicBricksKey').val()!='')
           $('#MagicBricksBtn').removeAttr('disabled'); 
    }
    
    function magicBricksForm(){
        var MagicBricksId       = $('#MagicBricksId').val();
        var MagicBricksSource   = $('#MagicBricksSource').val();
        var MagicBricksKey      = $('#MagicBricksKey').val();
        if(MagicBricksSource !='' && MagicBricksKey !=''){
            $.post('<?php echo $baseUrl?>/admin/magicbricksform', {Id:MagicBricksId,Source:MagicBricksSource,Key:MagicBricksKey},function(response){}) ;
        }
    }
    
    // 99 acres Form validations
    
    $('#AcresSource').blur(function(){
        if($('#AcresSource').val() == ''){
            $('#AcresBtn').attr('disabled','disabled');
            $("#AcresSourceErr").show();
        }else{
            $("#AcresSourceErr").hide();
        }
        acresBtn();
    });
    $('#AcresUserName').blur(function(){
        if($('#AcresUserName').val() == ''){
            $('#AcresBtn').attr('disabled','disabled');
            $("#AcresUserNameErr").show();
        }else{
            $("#AcresUserNameErr").hide();
        }
        acresBtn();
    });
    $('#AcresUserPswd').blur(function(){
        if($('#AcresUserPswd').val() == ''){
            $('#AcresBtn').attr('disabled','disabled');
            $("#AcresUserPswdErr").show();
        }else{
            $("#AcresUserPswdErr").hide();
        }
        acresBtn();
    });
    function acresBtn(){
        if($('#AcresSource').val()!='' && $('#AcresUserName').val()!='' && $('#AcresUserPswd').val()!=''){
            $('#AcresBtn').removeAttr('disabled'); 
        }
    }
    function acresForm(){
          
        var AcresId         = $('#AcresId').val();
        var AcresSource     = $('#AcresSource').val();
        var AcresUserName   = $('#AcresUserName').val();
        var AcresUserPswd   = $('#AcresUserPswd').val();
        
        if(AcresSource!='' && AcresUserName!='' && AcresUserName!=''){
            $.post('<?php echo $baseUrl?>/admin/acresform', {Id:AcresId,Source:AcresSource,UserName:AcresUserName,Pswd:AcresUserPswd},function(response){}) ;
        }
    }
    
    // sms api form
    
    $('#smsApiUsrName').blur(function(){
        if($('#smsApiUsrName').val() == ''){
            $('#smsApiBtn').attr('disabled','disabled');
            $("#smsApiUsrNameErr").show();
        }else{
            $("#smsApiUsrNameErr").hide();
        }
        smsApiBtn();
    });
    
    $('#smsApiUsrPswd').blur(function(){
         if($('#smsApiUsrPswd').val() == ''){
            $('#smsApiBtn').attr('disabled','disabled');
            $("#smsApiUsrPswdErr").show();
        }else{
            $("#smsApiUsrPswdErr").hide();
        }
        smsApiBtn();
    });
    function smsApiBtn(){
        if($('#smsApiUsrName').val()!='' && $('#smsApiUsrPswd').val()!='')
           $('#smsApiBtn').removeAttr('disabled'); 
    }
    function smsApiForm(){
        
        var smsApiId        = $('#smsApiId').val();
        var smsApiUsrName   = $('#smsApiUsrName').val();
        var smsApiUsrPswd   = $('#smsApiUsrPswd').val();
        
        if(smsApiUsrName!='' && smsApiUsrPswd!=''){
            $.post('<?php echo $baseUrl?>/admin/smsapiform', {Id:smsApiId,UserName:smsApiUsrName,Pswd:smsApiUsrPswd},function(response){}) ;
        }
    }
</script>