<?php $baseUrl = $this->basePath(); ?>
<link rel="STYLESHEET" type="text/css" href="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxgrid.css">
<link rel="stylesheet" type="text/css" href="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/skins/dhtmlxgrid_dhx_skyblue.css">
<link rel="STYLESHEET" type="text/css" href="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/ext/dhtmlxgrid_pgn_bricks.css">
<link rel="STYLESHEET" type="text/css" href="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxcombo.css">

<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxcommon.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxgrid.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxcombo.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxgridcell.js" ></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/ext/dhtmlxgrid_filter.js" ></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/ext/dhtmlxgrid_pgn.js"></script>
	  
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Leads
            <small>(Assigned Leads)</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Leads</li>
            <li class="active">Assigned Leads</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">
              <div class="box box-primary box-custom">
                <div class="box-header">
                <div class="col-md-6">
                  <h3 class="box-title">Assigned Leads</h3>
                  </div>
                  
                </div><!-- /.box-header -->
                
                <div class="box-header" ng-app="myApp" ng-controller="myCtrl">
                    <div class="col-md-3">
                    	<div class="form-group">                   
                            <select style="width: 100%;" class="form-control select2" name="userRole" ng-model="userRole" ng-change="getUsers(userRole)">
                                <option ng-repeat="UserRole in UserRoles" value="{{UserRole.Id}}" ng-selected="{{ UserRole.Id == '' }}" >
                                        {{UserRole.Name}}
                                </option>
                            </select>
                  	</div>
                    </div>
                    <div class="col-md-3">
                    	<div class="form-group"> 
                            <select style="width: 100%;" class="form-control select2" name="users" ng-model="users" ng-change="enableBtn(users)">
                                <option ng-repeat="Users in AllUsers" value="{{Users.Id}}" ng-selected="{{ Users.Id == '' }}" >
                                    {{Users.Name}}
                                </option>
                            </select>
                  	</div>
                    </div>
                    <div class="col-md-1"><button type="submit" class="btn btn-danger" ng-disabled="AssignButton" ng-click="assignLead()"> Reassign </button></div>                   
                </div>
                
                <div class="box-body">
                    <div id="loadingDiv" class="" style="display: none">
                        <img src="images/350.gif"  border="0" />
                    </div>
                    <div style="margin-left:15px" id="user_list">
                        <div id='preloader' style="display:none;" >
                        <img class=""src='images/animatedEllipse2.gif' border='0' style="width:50px;  left: 560px;position: absolute; top: 450px;z-index:2000"  ></div>	
                        <div id="manageuser" class="gridbox" style="width:100% !important; background-color:white; margin-left: 0px;"></div>
                        <div class="pagingWrap">
                            <div style="width:100%;float:left;" id="recinfoArea"></div>
                            <div id="pagingArea"></div>
                        </div>
                    </div> 
                    
                </div><!-- /.box-body -->
                <div class="box-header">
                  <div class="col-md-3"><div class="form-group">                   
                    <select class="form-control select2" style="width: 100%;" name="operationvalue" id="operationvalue" onchange="this.value">
                        <option value=''>Bulk Option</option>
                        <option value='delete'>Delete</option>
                        <!--<option value='inactive'>Inactivate</option>
                        <option value='active' id='activated'>Activate</option>-->
                    </select>
                  </div>
                  </div>
                  <div class="col-md-1 text-right"><button class="btn btn-primary" type="submit" onclick="bulkaction()"> Apply </button></div>
                </div>
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
          
          
        </section><!-- /.content -->
      </div>
<script src="<?php echo $baseUrl;?>/public/angular.min.js"></script>
<script>
        var notAssignedArr  =<?php echo $this->notAssignedArr;?>;
        var siteVisitArr    =<?php echo $this->siteVisitArr;?>;
        var meetingArr      =<?php echo $this->meetingArr;?>;
        var followUpArr     =<?php echo $this->followUpArr;?>;
        var notInterestedArr=<?php echo $this->notInterestedArr;?>;
        var notAnsweringArr  =<?php echo $this->notAnsweringArr;?>;
        
        
        
	var strgridURL='<?php echo $baseUrl;?>/admin/assignedleads';
	var mygrid = new dhtmlXGridObject('manageuser');
	mygrid.setSkin("dhx_skyblue");
	mygrid.setImagePath("<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/imgs/");
	mygrid.setHeader(",<b>Name</b>,<b>Mobile</b>,<b>Source</b>,<b>Project</b>,<b>Punch Date</b>,<b>Assigned To</b>,<b>Assigned Date</b>,<b>Next Meeting</b>,<b>Open By</b>,<b>Lead Status</b>,<b>Action</b>");							
	mygrid.attachHeader("#master_checkbox,#text_filter,#text_filter,#select_filter,#select_filter,#select_filter,#select_filter,#select_filter,#select_filter,#select_filter,#select_filter,");	
	mygrid.setInitWidths(" 30, 110, 90, 110, 90, 90, 90, 90, 90, 90, 100, *");
	mygrid.enableTooltips("false,false,false,false,false,false,false,false,false,false,false,false");
	mygrid.enableAutoHeight(true);   
	mygrid.setColAlign("center,left,left,left,left,left,left,left,left,left,left,left");
	mygrid.setColTypes("ch,ro,ro,ro,ro,ro,ro,ro,ro,ro,ro,ro");
	mygrid.setColSorting("na,str,str,str,str,str,str,str,str,str,str,str");
//	mygrid.enablePaging(true, 10, null, "pagingArea", true, "recinfoArea");
	mygrid.setPagingSkin("bricks");
	// mygrid.attachEvent("onXLS", function() { $("#preloader").show() });
	// mygrid.attachEvent("onXLE", function() { $("#preloader").hide() });		
	mygrid.attachEvent("onXLE", setRowColor);	
        mygrid.attachEvent("onFilterEnd", callBack);
	mygrid.init();							
	// mygrid.parse(<?php echo $this->jsonData?>,callBack,"json");
	mygrid.clearAndLoad(strgridURL,callBack,"json");
        
        
//        mygrid.setRowColor(2,"pink");
        
	function callBack(){	
		
	}
        
        
        function setRowColor(){
            
//            if(Object.keys(notAssignedArr).length >0){
//                $.each( notAssignedArr, function( key, value ) {
//                     mygrid.setRowColor(value,"pink");
////                    alert( key + ": " + value );
//                });
//           }
            
            if(Object.keys(siteVisitArr).length >0){
                $.each( siteVisitArr, function( key, value ) {
                     mygrid.setRowColor(value,"#ffc6b3");
//                    alert( key + ": " + value );
                });
           }
           
           if(Object.keys(meetingArr).length >0){
                $.each( meetingArr, function( key, value ) {
                     mygrid.setRowColor(value,"#DFF0D8");
//                    alert( key + ": " + value );
                });
           }
           
           if(Object.keys(followUpArr).length >0){
                $.each( followUpArr, function( key, value ) {
                     mygrid.setRowColor(value,"#D9EDF7");
//                    alert( key + ": " + value );
                });
           }
            
            if(Object.keys(notInterestedArr).length >0){
                $.each( notInterestedArr, function( key, value ) {
                     mygrid.setRowColor(value,"#ffffcc");
//                    alert( key + ": " + value );
                });
           }	 
            if(Object.keys(notAnsweringArr).length >0){
                $.each( notAnsweringArr, function( key, value ) {
                     mygrid.setRowColor(value,"#ffe0b3");
//                    alert( key + ": " + value );
                });
           }		
           return 1;
	}
	
	function deleteRow(id){
            SITEROOT = '<?php echo $baseUrl?>';
            $.post(SITEROOT+'/admin/updatestatus', {id:id,action:'delete',tableType:'USERLISTING'},function(response){
                if(response == '1')
                {
                    mygrid.clearAndLoad('<?php echo $baseUrl;?>/admin/manageleads',callBack,"json");
                }
            }) ;
	}
	
	function activeStatus(id){
            SITEROOT = '<?php echo $baseUrl?>';
            $.post(SITEROOT+'/admin/updatestatus', {id:id,action:'active',tableType:'USERLISTING'},function(response){
                if(response == '1')
                {
                    mygrid.clearAndLoad('<?php echo $baseUrl;?>/admin/manageleads',callBack,"json");
                }
            }) ;
		
	}
	
	function inActiveStatus(id){
            SITEROOT = '<?php echo $baseUrl?>';
            $.post(SITEROOT+'/admin/updatestatus', {id:id,action:'inactive',tableType:'USERLISTING'},function(response){
                if(response == '1')
                {
                        mygrid.clearAndLoad('<?php echo $baseUrl;?>/admin/manageleads',callBack,"json");
                }
            }) ;
	}
	
	
	function getSelectedIds(){
            var selected_rows = new Array();
            mygrid.forEachRow(function(id) {
                if(mygrid.cells(id, 0).getValue()==1){
                    selected_rows.push(id);
                }
            });		
            return selected_rows.join(",");
	}


	function bulkaction(){
            var action = $('#operationvalue').val();
            if(action!=''){
                var selectedIds = getSelectedIds();
                SITEROOT = '<?php echo $baseUrl?>';
                $.post(SITEROOT+'/admin/updatestatus', {selectedIds:selectedIds,action:action,tableType:'USERLISTING'},function(response){
                        if(response == '1')
                        {
                            mygrid.clearAndLoad('<?php echo $baseUrl;?>/admin/assignedleads',callBack,"json");
                        }
                }) ;		
            }
        }

	var app = angular.module("myApp", []);
        app.controller("myCtrl", function($scope, $http) {
            $scope.UserRoles    = <?php echo $this->allRoles?>;
            $scope.AllUsers     = [];
            $scope.AssignButton = true;
            $scope.getUsers     = function(role_id) {
                if(role_id!=''){
                    var url = "<?php echo $baseUrl?>/admin/getusersbyrole?callback=JSON_CALLBACK";
                        $http.post(url,{'role_id':role_id}) 
                        .success(function (data, status, headers, config) {
//                            console.log(data);
                            $scope.AllUsers = data;
                        })
                        .error(function (data, status, headers, config) {
                            //this always gets called
                            console.log(status);
                        });
                        return false;   
                }else{
                    $scope.AllUsers     = [];
                }            
            }
            
            $scope.enableBtn     = function(users) {
                if(users!=''){
                   $scope.AssignButton     = false;
                }else{
                   $scope.AssignButton     = true;
                }            
            }
            
            $scope.assignLead = function(){
                
                var leadIds = getSelectedIds();
//                
                if(leadIds!=''){
                    var url = "<?php echo $baseUrl?>/admin/reassignleadstouser?callback=JSON_CALLBACK";
                        $http.post(url,{'leadIds':leadIds,'userId':$scope.users}) 
                        .success(function (data, status, headers, config) {
                            console.log(data);
                            mygrid.clearAndLoad('<?php echo $baseUrl;?>/admin/assignedleads',callBack,"json");
//                            $scope.AllUsers = data;
                        })
                        .error(function (data, status, headers, config) {
                            //this always gets called
                            console.log(status);
                        });
                        return false;   
                }
            }
        });
</script>