<?php $baseUrl = $this->basePath(); ?>
<link rel="STYLESHEET" type="text/css" href="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxgrid.css">
<link rel="stylesheet" type="text/css" href="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/skins/dhtmlxgrid_dhx_skyblue.css">
<link rel="STYLESHEET" type="text/css" href="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/ext/dhtmlxgrid_pgn_bricks.css">
<link rel="STYLESHEET" type="text/css" href="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxcombo.css">

<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxcommon.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxgrid.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxcombo.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxgridcell.js" ></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/ext/dhtmlxgrid_filter.js" ></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/ext/dhtmlxgrid_pgn.js"></script>
	  
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Leads
            <small>(Manage Leads)</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Leads</li>
            <li class="active">Manage Leads</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">
              <div class="box box-primary box-custom">
                <div class="box-header">
                <div class="col-md-6">
                  <h3 class="box-title">Manage Leads</h3>
                  </div>
                  <div class="col-md-2 col-md-offset-4" style="padding-right:0px;">
                  <a href="<?php echo $baseUrl;?>/admin/addeditleads" class="btn btn-block btn-social btn-bitbucket pull-right" style="width:80%;">
                    <i class="fa fa-user"></i> Add Lead&nbsp; <i class="fa fa-angle-double-right"></i>
                  </a>
                  </div>
                </div><!-- /.box-header -->
                
                <div class="box-header" ng-app="myApp" ng-controller="myCtrl">
                    <div class="col-md-3">
                    	<div class="form-group">                   
                            <select style="width: 100%;" class="form-control select2" name="userRole" ng-model="userRole" ng-change="getUsers(userRole)">
                                <option ng-repeat="UserRole in UserRoles" value="{{UserRole.Id}}" ng-selected="{{ UserRole.Id == '' }}" >
                                        {{UserRole.Name}}
                                </option>
                            </select>
                  	</div>
                    </div>
                    <div class="col-md-3">
                    	<div class="form-group"> 
                            <select style="width: 100%;" class="form-control select2" name="users" ng-model="users" ng-change="enableBtn(users)">
                                <option ng-repeat="Users in AllUsers" value="{{Users.Id}}" ng-selected="{{ Users.Id == '' }}" >
                                    {{Users.Name}}
                                </option>
                            </select>
                  	</div>
                    </div>
                    <div class="col-md-1"><button type="submit" class="btn btn-danger" ng-disabled="AssignButton" ng-click="assignLead()"> Assign </button></div>                   
                </div>
                
                <div class="box-body">
                    <div id="loadingDiv" class="" style="display: none">
                        <img src="images/350.gif"  border="0" />
                    </div>
                    <div style="margin-left:15px" id="user_list">
                        <div id='preloader' style="display:none;" >
                        <img class=""src='images/animatedEllipse2.gif' border='0' style="width:50px;  left: 560px;position: absolute; top: 450px;z-index:2000"  ></div>	
                        <div id="manageuser" class="gridbox" style="width:100% !important; background-color:white; margin-left: 0px;"></div>
                        <div class="pagingWrap">
                            <div style="width:100%;float:left;" id="recinfoArea"></div>
                            <div id="pagingArea"></div>
                        </div>
                    </div> 
                    
                </div><!-- /.box-body -->
                <div class="box-header">
                  <div class="col-md-3"><div class="form-group">                   
                    <select class="form-control select2" style="width: 100%;" name="operationvalue" id="operationvalue" onchange="this.value">
                        <option value=''>Bulk Option</option>
                        <option value='delete'>Delete</option>
                        <!--<option value='inactive'>Inactivate</option>
                        <option value='active' id='activated'>Activate</option>-->
                    </select>
                  </div>
                  </div>
                  <div class="col-md-1 text-right"><button class="btn btn-primary" type="submit" onclick="bulkaction()"> Apply </button></div>
                </div>
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
          
          
        </section><!-- /.content -->
      </div>
<script src="<?php echo $baseUrl;?>/public/angular.min.js"></script>
<script>

	var strgridURL='<?php echo $baseUrl;?>/admin/manageleads';
	var mygrid = new dhtmlXGridObject('manageuser');
	mygrid.setSkin("dhx_skyblue");
	mygrid.setImagePath("<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/imgs/");
	mygrid.setHeader(",<b>Name</b>,<b>Mobile</b>,<b>Source</b>,<b>Project</b>,<b>Requirement</b>,<b>Punch Date</b>,<b>Open By</b>,<b>Action</b>");							
	mygrid.attachHeader("#master_checkbox,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,");	
	mygrid.setInitWidths(" 30, 150, 100, 150, 150, 150, 100, 100, *");
	mygrid.enableTooltips("false,false,false,false,false,false,false,false,false");
	mygrid.enableAutoHeight(true);   
	mygrid.setColAlign("center,left,left,left,left,left,left,left,left");
	mygrid.setColTypes("ch,ro,ro,ro,ro,ro,ro,ro,ro");
	mygrid.setColSorting("na,str,str,str,str,str,str,str,str");
	mygrid.enablePaging(true, 10, null, "pagingArea", true, "recinfoArea");
	mygrid.setPagingSkin("bricks");
        mygrid.attachEvent("onEditCell",doOnCellEdit);
	// mygrid.attachEvent("onXLS", function() { $("#preloader").show() });
	// mygrid.attachEvent("onXLE", function() { $("#preloader").hide() });		
	mygrid.attachEvent("onFilterEnd", callBack);													
	mygrid.init();							
	// mygrid.parse(<?php echo $this->jsonData?>,callBack,"json");
	mygrid.clearAndLoad(strgridURL,callBack,"json");
	function callBack(){
            $(function () {
               $('[data-toggle="tooltip"]').tooltip()
            })
	}
	
	function doOnCellEdit(stage,rowId,cellInd,newValue,oldValue){
            if(stage==2){
                SITEROOT = '<?php echo $baseUrl?>';
                $.post(SITEROOT+'/admin/updateleadintable', {id:rowId,value:newValue},function(response){}) ;
            }
            return true;
	}
	
	function deleteRow(id){
            SITEROOT = '<?php echo $baseUrl?>';
            $.post(SITEROOT+'/admin/updatestatus', {id:id,action:'delete',tableType:'LEADLISTING'},function(response){
                if(response == '1')
                {
                        mygrid.clearAndLoad('<?php echo $baseUrl;?>/admin/manageleads',callBack,"json");
                }
            }) ;
	}
	
//	function activeStatus(id){
//            SITEROOT = '<?php echo $baseUrl?>';
//            $.post(SITEROOT+'/admin/updatestatus', {id:id,action:'active',tableType:'USERLISTING'},function(response){
//                if(response == '1')
//                {
//                    mygrid.clearAndLoad('<?php echo $baseUrl;?>/admin/manageleads',callBack,"json");
//                }
//            }) ;
//		
//	}
//	
//	function inActiveStatus(id){
//		SITEROOT = '<?php echo $baseUrl?>';
//		$.post(SITEROOT+'/admin/updatestatus', {id:id,action:'inactive',tableType:'USERLISTING'},function(response){
//                    if(response == '1')
//                    {
//                            mygrid.clearAndLoad('<?php echo $baseUrl;?>/admin/manageleads',callBack,"json");
//                    }
//		}) ;
//	}
	
	
	function getSelectedIds(){
		var selected_rows = new Array();
		mygrid.forEachRow(function(id) {
                    if(mygrid.cells(id, 0).getValue()==1){
                            selected_rows.push(id);
                    }
		});		
		return selected_rows.join(",");
	}


	function bulkaction(){
            var action = $('#operationvalue').val();
            if(action!=''){
                var selectedIds = getSelectedIds();
                SITEROOT = '<?php echo $baseUrl?>';
                $.post(SITEROOT+'/admin/updatestatus', {selectedIds:selectedIds,action:action,tableType:'LEADLISTING'},function(response){
                    if(response == '1')
                    {
                        mygrid.clearAndLoad('<?php echo $baseUrl;?>/admin/manageleads',callBack,"json");
                    }
                }) ;		
            }
        }

	var app = angular.module("myApp", []);
        app.controller("myCtrl", function($scope, $http) {
            $scope.UserRoles    = <?php echo $this->allRoles?>;
            $scope.AllUsers     = [];
            $scope.AssignButton = true;
            $scope.getUsers     = function(role_id) {
                if(role_id!=''){
                    var url = "<?php echo $baseUrl?>/admin/getusersbyrole?callback=JSON_CALLBACK";
                        $http.post(url,{'role_id':role_id}) 
                        .success(function (data, status, headers, config) {
//                            console.log(data);
                            $scope.AllUsers = data;
                        })
                        .error(function (data, status, headers, config) {
                            //this always gets called
                            console.log(status);
                        });
                        return false;   
                }else{
                    $scope.AllUsers     = [];
                }            
            }
            
            $scope.enableBtn     = function(users) {
                if(users!=''){
                   $scope.AssignButton     = false;
                }else{
                   $scope.AssignButton     = true;
                }            
            }
            
            $scope.assignLead = function(){
                
                var leadIds = getSelectedIds();
//                
                if(leadIds!=''){
                    var url = "<?php echo $baseUrl?>/admin/assignleadstouser?callback=JSON_CALLBACK";
                        $http.post(url,{'leadIds':leadIds,'userId':$scope.users}) 
                        .success(function (data, status, headers, config) {
                            console.log(data);
                            mygrid.clearAndLoad('<?php echo $baseUrl;?>/admin/manageleads',callBack,"json");
//                            $scope.AllUsers = data;
                        })
                        .error(function (data, status, headers, config) {
                            //this always gets called
                            console.log(status);
                        });
                        return false;   
                }
                
                
            }
            
        });
</script>