<?php $baseUrl = $this->basePath(); ?>
<link rel="STYLESHEET" type="text/css" href="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxgrid.css">
<link rel="stylesheet" type="text/css" href="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/skins/dhtmlxgrid_dhx_skyblue.css">
<link rel="STYLESHEET" type="text/css" href="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/ext/dhtmlxgrid_pgn_bricks.css">
<link rel="STYLESHEET" type="text/css" href="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxcombo.css">

<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxcommon.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxgrid.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxcombo.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/dhtmlxgridcell.js" ></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/ext/dhtmlxgrid_filter.js" ></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/ext/dhtmlxgrid_pgn.js"></script>
	  
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Sources
            <small>(Manage Sources)</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Manage Sources</li>
          </ol>
        </section>

       <section class="content">
          <div class="row">
            <div class="col-xs-12">
              <div class="box box-primary box-custom">
              	<div class="box-header">
                <div class="col-md-12" style="padding-left:0px;">
                  <h3 class="box-title">Add/Edit Source</h3>
                  </div>                  
                </div><!-- /.box-header -->
                <div class="box-body">
                  <form  action="#" method="post" ng-controller="validateCtrl" name="myForm" novalidate>
                    <input type="text" name="sourceId" ng-model="sourceId" style="display:none;">
                    <div class="form-group-custom">
                        <label>Source Name</label>
                        <input type="text" name="SourceName" class="form-control" placeholder="Source Name" ng-model="SourceName" ng-blur="checkSourceName(SourceName)" required>
                        <span style="color:red;" ng-cloak ng-show="(myForm.SourceName.$dirty && myForm.SourceName.$invalid)">
                        <span ng-show="myForm.SourceName.$error.required">Project Name is required.</span>
                        </span>
                        <span id="SourceNameExists" style="display:none;color:red">Project Name already exists.</span>
                    </div>                        
                    <button class="btn btn-primary" type="submit" ng-disabled="(disableButton==true || myForm.$invalid )">Save</button>
                    <button class="btn btn-danger" type="button" style="margin-left:10px;" ng-click="cancelBtn()">Cancel</button>    
                </form>
                </div>
                <hr>
                <div class="box-header">
                <div class="col-md-12" style="padding-left:0px;">
                  <h3 class="box-title">Manage Sources</h3>
                  </div>                  
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div id="loadingDiv" class="" style="display: none">
                        <img src="images/350.gif"  border="0" />
                    </div>
                    <div id="user_list">
                        <div id='preloader' style="display:none;" >
                        <img class=""src='images/animatedEllipse2.gif' border='0' style="width:50px;  left: 560px;position: absolute; top: 450px;z-index:2000"  ></div>	
                        <div id="manageuser" class="gridbox" style="width:100% !important; background-color:white; margin-left: 0px;"></div>
                        <div class="pagingWrap">
                            <div style="width:100%;float:left;" id="recinfoArea"></div>
                            <div id="pagingArea"></div>
                        </div>
                    </div> 
                </div><!-- /.box-body -->
                <div class="box-header">
                  <div class="col-md-3" style='padding:0px;'>
                        <select class="form-control select2" style="width: 100%;" name="operationvalue" id="operationvalue" onchange="this.value">
                            <option value=''>Bulk Option</option>
                            <option value='delete'>Delete</option>
                            <option value='inactive'>Inactivate</option>
                            <option value='active' id='activated'>Activate</option>
                        </select>
                  </div>
                   <div class="col-md-1 text-right"><button class="btn btn-primary" type="submit" onclick="bulkaction()"> Apply </button></div>
                </div>
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
          
          
        </section><!-- /.content -->
      </div>
<script src="<?php echo $baseUrl;?>/public/angular.min.js"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script>

	var strgridURL='<?php echo $baseUrl;?>/admin/sources';
	var mygrid = new dhtmlXGridObject('manageuser');
	mygrid.setSkin("dhx_skyblue");
	mygrid.setImagePath("<?php echo $baseUrl;?>/public/dhtmlxgrid/codebase/imgs/");
	mygrid.setHeader(",<b>Source Name</b>,<b>Last Updated By</b>,<b>Last Updated Time</b>,<b>Action</b>");							
	mygrid.attachHeader("#master_checkbox,#text_filter,,,");	
	mygrid.setInitWidths(" 30, 490, 150, 150, *");
	mygrid.enableTooltips("false,false,false,false,false");
	mygrid.enableAutoHeight(true);   
	mygrid.setColAlign("center,left,left,left,left");
	mygrid.setColTypes("ch,ro,ro,ro,ro");
	mygrid.setColSorting("na,str,str,str,str");
	mygrid.enablePaging(true, 10, null, "pagingArea", true, "recinfoArea");
	mygrid.setPagingSkin("bricks");
	// mygrid.attachEvent("onXLS", function() { $("#preloader").show() });
	// mygrid.attachEvent("onXLE", function() { $("#preloader").hide() });		
	mygrid.attachEvent("onFilterEnd", callBack);													
	mygrid.init();							
	// mygrid.parse(<?php echo $this->jsonData?>,callBack,"json");
	mygrid.clearAndLoad(strgridURL,callBack,"json");
	function callBack(){
            $(function () {
               $('[data-toggle="tooltip"]').tooltip()
            })	
		
	}
	
	function deleteRow(id){
		SITEROOT = '<?php echo $baseUrl?>';
		$.post(SITEROOT+'/admin/updatestatus', {id:id,action:'delete',tableType:'SOURCELISTING'},function(response){
			if(response == '1')
			{
				mygrid.clearAndLoad('<?php echo $baseUrl;?>/admin/sources',callBack,"json");
			}
		
		}) ;
	}
	
	function activeStatus(id){
		SITEROOT = '<?php echo $baseUrl?>';
		$.post(SITEROOT+'/admin/updatestatus', {id:id,action:'active',tableType:'SOURCELISTING'},function(response){
			if(response == '1')
			{
				mygrid.clearAndLoad('<?php echo $baseUrl;?>/admin/sources',callBack,"json");
			}
		
		}) ;
		
	}
	
	function inActiveStatus(id){
		SITEROOT = '<?php echo $baseUrl?>';
		$.post(SITEROOT+'/admin/updatestatus', {id:id,action:'inactive',tableType:'SOURCELISTING'},function(response){
			// alert(response);
			if(response == '1')
			{
				mygrid.clearAndLoad('<?php echo $baseUrl;?>/admin/sources',callBack,"json");
			}
		}) ;
	}
	
	
	function getSelectedIds(){
		var selected_rows = new Array();
		mygrid.forEachRow(function(id) {
			if(mygrid.cells(id, 0).getValue()==1){
				selected_rows.push(id);
			}
		});		
		return selected_rows.join(",");
	}


	function bulkaction(){
        var action = $('#operationvalue').val();
        if(action!=''){
            var selectedIds = getSelectedIds();
            SITEROOT = '<?php echo $baseUrl?>';
            $.post(SITEROOT+'/admin/updatestatus', {selectedIds:selectedIds,action:action,tableType:'SOURCELISTING'},function(response){
                if(response == '1')
                {
                    mygrid.clearAndLoad('<?php echo $baseUrl;?>/admin/sources',callBack,"json");
                }
            }) ;		
        }
    }

    var app = angular.module('myApp', []);
    var sourceDetail         = <?php if(isset($this->sourceDetail)) echo $this->sourceDetail; else echo '{}'?>;
    
    app.controller('validateCtrl', function($scope,$http) {
        
       $scope.disableButton = false;
       if(Object.keys(sourceDetail).length >0){
           $scope.sourceId = sourceDetail.id;
           $scope.SourceName = sourceDetail.source_name;
       }
        $scope.cancelBtn = function(){
            window.location.href = '<?php echo $baseUrl?>/admin/sources';
        }
        $scope.checkSourceName = function(sourceName){
            var url = "<?php echo $baseUrl?>/admin/checksourcename?callback=JSON_CALLBACK";
            $http.post(url,{'sourceName':sourceName}) 
            .success(function (data, status, headers, config) {
                console.log(data);
                if(data==1 && sourceName!=sourceDetail.source_name){
                    $('#SourceNameExists').show();
                    $scope.disableButton = true;
                }else{
                    $('#SourceNameExists').hide();
                    $scope.disableButton = false;
                }
            })
            .error(function (data, status, headers, config) {
                //this always gets called
                console.log(status);
            });
            return false;  
        }
    });
    
    // ng-app was ommitted from the html so that
    // we can manually bootstray (initialize)
    // angular after a delay to simulate the 
    // actual code being loaded later
    setTimeout(function(){
      angular.element(document).ready(function() {
          //console.log('document Ready');
        angular.bootstrap(document, ['myApp']);
      });  
    },1000);
</script>