<?php $baseUrl = $this->basePath();

//echo $baseUrl;exit;


?>
<!-- Content Wrapper. Contains page content -->
    <!-- Angular js file -->
   <style>
    [ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {
      display: none !important;
    }
  </style>
  
 <link href="<?php echo $baseUrl;?>/public/date/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">    
<div class="content-wrapper" ng-app="myApp">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Update Lead
            <small>(Assign Update Status)</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li>Update Lead</li>
            <li class="active">Assign Update Status</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Small boxes (Stat box) -->
          <!-- /.row -->
          <!-- Main row -->
          <div class="row">
            <!-- Left col -->
            <section class="col-lg-12 connectedSortable">
              <!-- Add user form-->
              <div class="box box-primary box-custom">
                <div class="box-header with-border">
                  <h3 class="box-title">Assign Update Status</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <section class="content">

          <!-- SELECT2 EXAMPLE -->
          <div class="box box-default" style="margin-top:30px;"  ng-controller="updateLead">
            <!-- /.box-header -->
            <div class="box-body">
              <form method="post" name="myForm" novalidate>
              <div class="row">
                <div class="col-md-6" style="margin-top:30px;">
                  <div class="form-group">
                    <input type="hidden"  ng-model="formData.leadId" name="leadId">
                    <label>Name <span class="mandatory">*</span></label>
                    <input class="form-control" type="text" placeholder="Enter ..." name="CustomerName" ng-model="formData.CustomerName" required>
                    <span style="color:red;" ng-cloak ng-show="(myForm.CustomerName.$dirty && myForm.CustomerName.$invalid)">
                    <span ng-show="myForm.CustomerName.$error.required">Email is required.</span></span>
                  </div><!-- /.form-group -->
                  <div class="form-group">
                    <label>Lead Source <span class="mandatory">*</span></label>
                    <select class="form-control select2" style="width: 100%;" name="SourceOfEnquiry" ng-model="formData.SourceOfEnquiry"  ng-change="setSourceOfEnquiry(formData.SourceOfEnquiry)">
                      <option ng-repeat="allSource in allSources" value="{{allSource.Id}}" <?php if(count($this->formData[0])){?>ng-selected="{{ allSource.Id == <?php echo $this->formData[0]['source_of_enquiry']?> }}" <?php }?>>
                            {{allSource.Name}}
                      </option>
                    </select>
                  </div><!-- /.form-group -->
                  <div class="form-group">
                    <label>Project Name <span class="mandatory">*</span></label>
                    <select class="form-control select2" style="width: 100%;" name="ProjectInterested" ng-model="formData.ProjectInterested" ng-change="setProjectInterested(formData.ProjectInterested)">
                        <option ng-repeat="allProject in allProjects" value="{{allProject.Id}}" <?php if(count($this->formData[0])){?>ng-selected="{{ allProject.Id == <?php echo $this->formData[0]['project_interested']?> }}" <?php }?>>
                            {{allProject.Name}}
                        </option>
                    </select>
                  </div>
                   <!-- Date and time range -->
                  <div class="form-group">
                    <label>Punch Date <span class="mandatory">*</span></label>
                    <div class="input-group">
                      <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                      </div>
                        <input type="text" class="form-control pull-right form_datetime" ng-disabled="true" name="PunchDate" ng-model="formData.PunchDate" required>
                    </div><!-- /.input group -->
                    
                      <span style="color:red" ng-cloak ng-show="myForm.PunchDate.$dirty && myForm.PunchDate.$invalid">
                        <span  ng-show="myForm.PunchDate.$error.required">Punch Date is required</span>
                      </span>
                  </div><!-- /.form group -->
                  
                  <div class="form-group">
                    <label>Budget</label>
                    <input class="form-control" type="text" placeholder="Enter..." name="Budget" ng-model="formData.Budget">
                  </div><!-- /.form-group -->
                </div><!-- /.col -->
                <div class="col-md-6" style="margin-top:30px; margin-bottom:30px;">
                  <div class="form-group">
                    <label>Mobile No. <span class="mandatory">*</span></label>
                    <input class="form-control" disabled ng-model="formData.MobileNumber">
                    <input type="text" name="MobileNumber" ng-model="formData.MobileNumber" style="display:none">
                <!--    <input class="form-control" type="text" placeholder="i.e 9999888866" ng-minlength="10" ng-maxlength="10" name="MobileNumber" ng-model="formData.MobileNumber" required>
                    <span style="color:red" ng-cloak ng-show="myForm.MobileNumber.$dirty && myForm.MobileNumber.$invalid">
                    <span  ng-show="myForm.MobileNumber.$error.required || myForm.MobileNumber.$error.number">Invalid Phone</span>
                    <span  ng-show="(myForm.MobileNumber.$error.minlength || myForm.MobileNumber.$error.maxlength) ">Mobile Number should be of 10 digits</span>
                    </span>-->
                  </div><!-- /.form-group -->
                  <div class="form-group">
                    <label>Alternate No.</label>
                    <input class="form-control" type="text" placeholder="i.e 9999888866" ng-minlength="10" ng-maxlength="10" name="AlternateName" ng-model="formData.AlternateName" ng-blur="CheckMobile(formData.AlternateName,'AlternateName')" >
                    <span style="color:red" ng-cloak ng-show="myForm.AlternateName.$dirty && myForm.AlternateName.$invalid">
                    <span  ng-show="myForm.AlternateName.$error.number">Invalid Phone</span>
                    <span  ng-show="(myForm.AlternateName.$error.minlength || myForm.AlternateName.$error.maxlength) ">Alternate Number should be 10 of digits</span>
                    </span>
                    <span id="noExistsMsg_AlternateName" style="display:none;color:red">Mobile Number already exists.</span>
                  </div><!-- /.form-group -->
                  <div class="form-group">
                    <label>Other No.</label>
                    <input class="form-control" type="text" placeholder="i.e 9999888866" ng-minlength="10" ng-maxlength="10" name="OtherName" ng-model="formData.OtherName" ng-blur="CheckMobile(formData.OtherName,'OtherName')">
                    <span style="color:red" ng-cloak ng-show="myForm.OtherName.$dirty && myForm.OtherName.$invalid">
                    <span  ng-show="myForm.OtherName.$error.number">Invalid Phone</span>
                    <span  ng-show="(myForm.OtherName.$error.minlength || myForm.OtherName.$error.maxlength) ">Other Number should be 10 of digits</span>
                    </span>
                    <span id="noExistsMsg_OtherName" style="display:none;color:red">Mobile Number already exists.</span>
                  </div><!-- /.form-group -->
                  <div class="form-group">
                    <label>Email ID</label>
                    <input type="email" placeholder="Enter email" class="form-control" name="EmailAddress" ng-model="formData.EmailAddress">
                  </div><!-- /.form-group -->                   
                </div><!-- /.col -->                
              </div><!-- /.row -->
              <div class="box-footer-customize">
                 <button class="btn btn-primary" type="button" ng-click="updateLeadForm()" ng-disabled="(disableForm==true || myForm.$invalid )">Update</button>
                <button class="btn btn-danger" type="button" style="margin-left:10px;">Cancel</button>
                <!---<button class="btn btn-warning" type="button" style="margin-left:10px;">Status Update</button>-->
                <img id="updateLeadLoader" src="<?php echo $baseUrl;?>/public/dist/img/Snakes_chasing.gif" style="Padding-left:15px; width:45px;display: none;" >
              </div>
              </form>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
          
			<!----Second Step--->
	<div class="box box-default"  ng-controller="updateStatus"> 
            <div class="checkbox box-body" style="background-color:#ecf0f5; margin-top:30px;">
                <label>
                    <input type="checkbox" ng-click="showLeadStatusDiv()" ng-model="showLeadDiv" > Update Lead Status
                </label>
            </div>
          <div class="box-body" <?php if(count($this->leadUpdatesHistory)==0){?>style="display:none"<?php }?> id="leadStatusDiv">
            <form method="post" name="myForm2" novalidate>
            <input type="hidden"  ng-model="leadStatusForm.leadId" name="leadId">
            <div class="row" >
            <div class="col-xs-12 col-sm-12 col-md-12">
              <!-- jQuery Knob -->
              <div class="box-solid" style="background-color:#ecf0f5;border:1px solid #d2d6de;;margin-bottom:30px">               
                <div class="box-body">
                  <div class="row">
                    <div class="col-md-2 col-sm-12 col-xs-12 text-center">                  
                     <label>Client Type</label>                      	                    
                    </div><!-- ./col -->
                    <div class="col-md-2 col-sm-3 col-xs-3 text-center">                    	
                      	<input type="radio" name="clientType" ng-model="leadStatusForm.clientType" class="minimal" value=1 > 
                        <label> Client</label>                    
                    </div><!-- ./col -->
                    <div class="col-md-2 col-sm-3 col-xs-3 text-center">                    	
                      	<input type="radio" name="clientType" ng-model="leadStatusForm.clientType" class="minimal" value=2> 
                        <label> Broker</label>                     
                    </div><!-- ./col -->                  
                  </div><!-- /.row -->                 
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col --> 
          </div>
        
            <div class="row" ng-show="(leadStatusForm.clientType)">
            <div class="col-xs-12 col-sm-12 col-md-12">
              <!-- jQuery Knob -->
              <div class="box-solid" style="background-color:#ecf0f5;border:1px solid #d2d6de;">               
                <div class="box-body">
                  <div class="row">
                    <div class="col-md-4 col-sm-6 col-xs-6 text-center">
                        <input type="radio" name="statusType" ng-model="leadStatusForm.statusType" class="minimal" value=1 > Interested                      
                    </div><!-- ./col -->
                    <div class="col-md-4 col-sm-6 col-xs-6 text-center">
                      <input type="radio" name="statusType" ng-model="leadStatusForm.statusType" class="minimal" value=2 > Not Interested                        
                    </div><!-- ./col -->
                    <div class="col-md-4 col-sm-6 col-xs-6 text-center">
                      <input type="radio" name="statusType" ng-model="leadStatusForm.statusType" class="minimal" value=3 > Not Answering                      
                    </div><!-- ./col -->                   
                  </div><!-- /.row -->
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
          
          
          <div class="row" style="margin-top:30px;" ng-show="(leadStatusForm.statusType=='1')">
            <div class="col-xs-12 col-sm-12 col-md-12">
            <!-- jQuery Knob -->
            <div class="box-solid" style="background-color:#ecf0f5;border:1px solid #d2d6de;">               
              <div class="box-body">
                <div class="row">
                  <div class="col-md-4 col-sm-6 col-xs-6 text-center">
                    <input type="radio" name="interestedType" ng-model="leadStatusForm.interestedType" class="minimal" value=1> For Site Visit                    
                  </div><!-- ./col -->
                  <div class="col-md-4 col-sm-6 col-xs-6 text-center">
                    <input type="radio" name="interestedType" ng-model="leadStatusForm.interestedType" class="minimal" value=2> For Meeting                      
                  </div><!-- ./col -->
                  <div class="col-md-4 col-sm-6 col-xs-6 text-center">
                    <input type="radio" name="interestedType" ng-model="leadStatusForm.interestedType" class="minimal" value=3> For Follow Up                      
                  </div><!-- ./col -->                   
                </div><!-- /.row -->
              </div><!-- /.box-body -->
            </div><!-- /.box -->
          </div><!-- /.col --> 
        </div><!-- /.row -->
          
          
          <div class="row" style="margin-top:30px;" ng-show="(leadStatusForm.statusType=='2')"> 
            <div class="col-xs-12 col-sm-12 col-md-12">
              <!-- jQuery Knob -->
              <div class="box-solid" style="background-color:#ecf0f5;border:1px solid #d2d6de;">               
                <div class="box-body">
                  <div class="row">
                  <div class="col-md-2 col-sm-12 col-xs-12 text-center">                  
                     <label>Bogus Lead</label>                                           
                    </div><!-- ./col -->
                    <div class="col-md-2 col-sm-3 col-xs-3 text-center">                     
                       <input type="radio"  name="bogusLead"  ng-model="leadStatusForm.bogusLead" class="minimal" value="1"> 
                        <label> Yes</label>                    
                    </div><!-- ./col -->
                    <div class="col-md-2 col-sm-3 col-xs-3 text-center">                     
                       <input type="radio"  name="bogusLead"  ng-model="leadStatusForm.bogusLead" class="minimal" value="2"> 
                        <label> No</label>                     
                    </div><!-- ./col -->                                      
                  </div><!-- /.row -->                 
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col --> 
          </div>
          
          <div class="row" style="margin-top:10px;">
            <div class="col-xs-12 col-sm-12 col-md-12">
              <!-- jQuery Knob -->
              <div class="box-solid">               
                <div class="box-body">
                  <div class="row">
                    <div class="col-md-4 col-sm-6 col-xs-6" ng-show="(leadStatusForm.statusType=='1' && leadStatusForm.interestedType=='1')">
                       <!-- Date and time range -->
                          <div class="form-group">
                            <label>Site Visit Date & Time</label>
                            <div class="input-group">
                              <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                              </div>
                              <input type="text" class="form-control pull-right form_datetime1" name="dateTimeValue"  ng-model="leadStatusForm.dateTimeValue">
                            </div><!-- /.input group -->
                          </div><!-- /.form group -->                                      
                    </div><!-- ./col -->
                    
                    <div class="col-md-4 col-sm-6 col-xs-6" ng-show="(leadStatusForm.statusType=='1' && leadStatusForm.interestedType=='2')">
                       <!-- Date and time range -->
                        <div class="form-group">
                          <label>Meeting Date & Time</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" class="form-control pull-right form_datetime2" name="dateTimeValue"  ng-model="leadStatusForm.dateTimeValue">
                          </div><!-- /.input group -->
                        </div><!-- /.form group -->                    
                    </div><!-- ./col -->
                    
                    <div class="col-md-4 col-sm-6 col-xs-6" ng-show="(leadStatusForm.statusType=='1' && leadStatusForm.interestedType=='3')">
                       <!-- Date and time range -->
                        <div class="form-group">
                          <label>Follow Up Date & Time</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" class="form-control pull-right form_datetime3" name="dateTimeValue"  ng-model="leadStatusForm.dateTimeValue" >
                          </div><!-- /.input group -->
                        </div><!-- /.form group -->                     
                    </div><!-- ./col -->                   
                  </div><!-- /.row -->
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col --> 
          </div>
          
          
        <div class="row" ng-show="(leadStatusForm.statusType=='1' && leadStatusForm.interestedType)">
            <div class="col-xs-12 col-sm-12 col-md-12">
              <!-- jQuery Knob -->
              <div class="box-solid" style="background-color:#ecf0f5;border:1px solid #d2d6de;;margin-bottom:30px">               
                <div class="box-body">
                  <div class="row">
                  <div class="col-md-2 col-sm-12 col-xs-12 text-center">                  
                     <label>Rate this lead</label>                      	                    
                    </div><!-- ./col -->
                    <div class="col-md-2 col-sm-3 col-xs-3 text-center">                    	
                      	<input type="radio" name="rateThisLead" ng-model="leadStatusForm.rateThisLead" class="minimal" value=1 > 
                        <label> Avg.</label>                    
                    </div><!-- ./col -->
                    <div class="col-md-2 col-sm-3 col-xs-3 text-center">                    	
                      	<input type="radio" name="rateThisLead" ng-model="leadStatusForm.rateThisLead" class="minimal" value=2> 
                        <label> Medium</label>                     
                    </div><!-- ./col -->
                    <div class="col-md-2 col-sm-3 col-xs-3 text-center">                    	
                      	<input type="radio" name="rateThisLead" ng-model="leadStatusForm.rateThisLead" class="minimal" value=3>
                        <label> Good</label>                     
                    </div><!-- ./col --> 
                    <div class="col-md-2 col-sm-3 col-xs-3 text-center">                    	
                      	<input type="radio" name="rateThisLead" ng-model="leadStatusForm.rateThisLead" class="minimal" value=4>
                        <label> Hot</label>                     
                    </div><!-- ./col -->                   
                  </div><!-- /.row -->                 
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col --> 
          </div>
          
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <label>Description</label>
                <textarea class="form-control" rows="3" ng-model="leadStatusForm.description"></textarea>                         
            </div><!-- /.col --> 
          </div>
            <div class="box-footer">
                <button class="btn btn-primary" ng-click="submitLeadStatus();"  >Submit</button>
                <img id="updateStatusLoader" src="<?php echo $baseUrl;?>/public/dist/img/Snakes_chasing.gif" style="Padding-left:15px; width:45px;display: none;" >
            </div>
            </form>
            </div><!-- /.box-body -->
            
          </div>
        </section>
              </div>
              <!-- /End of Add user form -->

             <!-- Add new Graph ----------------------------------------------------><!-- /.box -->             

            </section><!-- /.Left col -->            
          </div><!-- /.row (main row) -->

          <div class="box box-default" style="margin-top:30px;">
            <!-- /.box-header -->
            <div class="box-body">
              <div class="row">
               <div class="col-md-12">
              <!-- The time line -->
              <ul class="timeline">
               <h4>Status History</h4><hr>
                <!-- timeline item -->
                <?php if(count($this->leadUpdatesHistory)){
                    foreach($this->leadUpdatesHistory as $leadHistory){
//                       echo '<pre>';print_r($leadHistory);
                ?> 
                    <li>                 
                        <div class="timeline-item">                    
                          <h3 class="timeline-header text-red">
                          <?php 
                            if($leadHistory['status_type'] == 1)                              
                                echo 'Interested';                              
                            elseif($leadHistory['status_type'] == 2)
                                echo 'Not Interested ';
                            else  
                                echo 'Not Answering';
                            
                            if($leadHistory['last_feedback']!='')
                                echo '  ['.$leadHistory['last_feedback'].']';
                            
                              ?></h3>
                          <div class="timeline-body">
                            <strong>Next Visit :</strong> <?php if($leadHistory['date_time_value'] != '0000-00-00 00:00:00.0') echo $leadHistory['date_time_value']; else echo '';?><br>
                            <strong>Update By :</strong> <?php echo $leadHistory['updated_by'];?><br>
                            <strong>Updated On :</strong> <?php echo $leadHistory['updated_on'];?><br>
                            <?php //if{?>  
                            <strong>Rating :</strong> <?php if($leadHistory['lead_rating'] != '0'){
//                               echo $leadHistory['lead_rating']; 
                                
                              if($leadHistory['lead_rating'] == 1)                              
                                echo 'Average';                              
                              elseif($leadHistory['lead_rating'] == 2)
                                echo 'Medium';
                              elseif($leadHistory['lead_rating'] == 3)
                                echo 'Good';
                              else  
                                echo 'Hot';
                                
                                
                            } else echo '';?>
                          </div>                    
                        </div>
                    </li>
                <?php        
                    }   
                } 
                ?>
                              
              </ul>
            </div>               
              </div><!-- /.row -->
              <!--<div class="box-footer-customize">
                    ================= footer content =======================
                </div>---->
            </div><!-- /.box-body -->
          </div>
        </section><!-- /.content -->
      </div>
  
    <script src="<?php echo $baseUrl;?>/public/plugins/jQuery/jQuery-2.1.4.min.js"></script>
  
    <script src="<?php echo $baseUrl;?>/public/angular.min.js"></script>
    <script type="text/javascript" src="<?php echo $baseUrl;?>/public/date/bootstrap-datetimepicker.js" charset="UTF-8"></script>
    <script type="text/javascript" src="<?php echo $baseUrl;?>/public/date/bootstrap-datetimepicker.fr.js" charset="UTF-8"></script>




<script type="text/javascript">
    $('.form_datetime').datetimepicker({
        //language:  'fr',
        weekStart: 1,
        todayBtn:  1,
        autoclose: 1,
        startDate:new Date(),
        todayHighlight: 1,
        startView: 2,
        forceParse: 0,
        showMeridian: 1
    });
	$('.form_datetime1').datetimepicker({
        //language:  'fr',
        weekStart: 1,
        todayBtn:  1,
        autoclose: 1,
        todayHighlight: 1,
        startDate:new Date(),
        startView: 2,
        forceParse: 0,
        showMeridian: 1
    });
	$('.form_datetime2').datetimepicker({
        //language:  'fr',
        weekStart: 1,
        todayBtn:  1,
        autoclose: 1,
        todayHighlight: 1,
        startDate:new Date(),
        startView: 2,
        forceParse: 0,
        showMeridian: 1
    });
	$('.form_datetime3').datetimepicker({
        //language:  'fr',
        weekStart: 1,
        todayBtn:  1,
        autoclose: 1,
        todayHighlight: 1,
        startDate:new Date(),
        startView: 2,
        forceParse: 0,
        showMeridian: 1
    });
	</script>
  <script>
    var app = angular.module('myApp', []);
    app.controller('updateLead', function($scope, $http) {
        $scope.allSources           = <?php echo $this->allSources?>;
        $scope.allProjects          = <?php echo $this->allProjects?>;
        $scope.disableForm = false;
//        $scope.AlternateName = '';
//        $scope.formData.OtherName    = '';
        var str = '<?php echo $this->formData[0]['punch_date']?>';
        var res = str.substr(0, 16);
        $scope.formData = {
            leadId               : '<?php echo $this->formData[0]['id']?>',
            SourceOfEnquiry      : '<?php echo $this->formData[0]['source_of_enquiry']?>',
            ProjectInterested    : '<?php echo $this->formData[0]['project_interested']?>',
            CustomerName         : '<?php echo $this->formData[0]['customer_name']?>',
            MobileNumber         : parseInt('<?php echo base64_decode($this->formData[0]['mobile'])?>'),
            AlternateName        : parseInt('<?php if($this->formData[0]['alt_no']!='') echo base64_decode($this->formData[0]['alt_no'])?>'),
            OtherName            : parseInt('<?php if($this->formData[0]['other_no']!='') echo base64_decode($this->formData[0]['other_no'])?>'),
            EmailAddress         : '<?php echo $this->formData[0]['email']?>',
            Address              : '<?php echo $this->formData[0]['address']?>',
            PunchDate            : res,
            Budget               : '<?php if($this->formData[0]['budget']!=0) echo $this->formData[0]['budget']?>',
            Requirement          : '<?php echo $this->formData[0]['requirement']?>',
        }
        
        $scope.setProjectInterested   = function(project){
//            console.log(project);
            $scope.formData.ProjectInterested = project;
        };
        $scope.setSourceOfEnquiry   = function(source){
//            console.log(source);
            $scope.formData.SourceOfEnquiry = source;
        };
        $scope.updateLeadForm      = function(){
            var url = "<?php echo $baseUrl?>/admin/updateleadstatus?callback=JSON_CALLBACK";
            $('#updateLeadLoader').show();
//            console.log($scope.formData);
            $http.post(url,$scope.formData) 
            .success(function (data, status, headers, config) {
                console.log(data);
                $('#updateLeadLoader').hide();
                return false;
            })
            .error(function (data, status, headers, config) {
                //this always gets called
                console.log(status);
            });
            return false;   
            console.log($scope.formData);
        };
        
        $scope.CheckMobile = function(mobileNumber,fieldName){
             
             
//             alert($scope.formData.AlternateName);
//             
//             return false;
            var mobileMatched = 0;
            if(isNaN($scope.formData.AlternateName)==false){
                if($scope.formData.AlternateName == $scope.formData.MobileNumber){
                    $scope.disableForm = true;
                    mobileMatched = 1;
                    $('#noExistsMsg_AlternateName').text('Alternate Number and Mobile Number cannot be same.').show();
                }else if($scope.formData.AlternateName == $scope.formData.OtherName){

                     $scope.disableForm = true;
                     mobileMatched = 1;
                     $('#noExistsMsg_AlternateName').text('Alternate Number and Other Number cannot be same.').show();
                }
            }
            if(isNaN($scope.formData.OtherName)==false){
                if($scope.formData.OtherName == $scope.formData.MobileNumber){
                    $scope.disableForm = true;
                    mobileMatched = 1;
                    $('#noExistsMsg_OtherName').text('Other Number and Mobile Number cannot be same.').show();
                }else if($scope.formData.AlternateName == $scope.formData.OtherName){
                     $scope.disableForm = true;
                     mobileMatched = 1;
                      $('#noExistsMsg_OtherName').text('Other Number and Alternate Number cannot be same.').show();
                }
            }
            
            if(mobileMatched == 0){
                var url = "<?php echo $baseUrl?>/admin/checkmobilenumber";
                $http.post(url,{'mobileNumber':mobileNumber}) 
                .success(function (data, status, headers, config) {
                    if(data==1){
                        if(fieldName=='AlternateName'){
                            if($scope.formData.AlternateName  != parseInt('<?php echo base64_decode($this->formData[0]['alt_no'])?>')){
                                $('#noExistsMsg_'+fieldName).text('').text('Mobile Number already exists').show();
                                $scope.disableForm = true;
                            }else $('#noExistsMsg_'+fieldName).hide();
                        }else if(fieldName=='OtherName'){
                            if($scope.formData.OtherName  != parseInt('<?php echo base64_decode($this->formData[0]['other_no'])?>')){
                                $('#noExistsMsg_'+fieldName).text('').text('Mobile Number already exists').show();
                                $scope.disableForm = true;
                            }else $('#noExistsMsg_'+fieldName).hide();
                        }else{
                            $('#noExistsMsg_'+fieldName).text('').text('Mobile Number already exists').show();
                            $scope.disableForm = true;
                        }
                    }else{
                        $('#noExistsMsg_'+fieldName).hide();
                        $scope.disableForm = false;
//                        $scope.MobileNumber   = $scope.disbledMobileNumber;
                    }
                   console.log(data); 
                // }

                })
                .error(function (data, status, headers, config) {
                    //this always gets called
                    console.log(status);
                });
            }
            return false;
            
        }
        
    });
   app.controller('updateStatus', function($scope, $http) {
        
        var leadUpdatesCurrent = <?php echo $this->leadUpdatesCurrent?>;
//        console.log(leadUpdatesCurrent.status_type);
        if(Object.keys(leadUpdatesCurrent).length > 0){
            $scope.leadStatusForm = {
                leadId               :  '<?php echo $this->formData[0]['id']?>',
                statusType           :  leadUpdatesCurrent.status_type,
                interestedType       :  leadUpdatesCurrent.interested_type,
                bogusLead            :  leadUpdatesCurrent.bogus_lead,
                dateTimeValue        :  leadUpdatesCurrent.date_time_value.substr(0, 16),
                rateThisLead         :  leadUpdatesCurrent.lead_rating,
                clientType           :  leadUpdatesCurrent.client_type,
                description          :  leadUpdatesCurrent.last_feedback,
            }
            $scope.showLeadDiv = true;
        }else{
            $scope.leadStatusForm = {
                leadId               :  '<?php echo $this->formData[0]['id']?>'
            }
        }
           

       $scope.showLeadStatusDiv = function(){
//            console.log($scope.showLeadDiv);
            if($scope.showLeadDiv == true)
                $('#leadStatusDiv').show('slow');
            else
                $('#leadStatusDiv').hide('slow');
       }
       
        
//        $scope.leadStatusResetForm = {
//            statusType           :  '',
//            interestedType       :  '',
//            bogusLead            :  '',
//            dateTimeValue        :  '',
//            rateThisLead         :  '',
//            clientType           :  '',
//            description          :  ''
//        }
       
       $scope.submitLeadStatus = function(){
           
//         console.log($scope.leadStatusForm);  
            var url = "<?php echo $baseUrl?>/admin/submitleadstatus?callback=JSON_CALLBACK";
            $('#updateStatusLoader').show();
            $http.post(url,$scope.leadStatusForm) 
            .success(function (data, status, headers, config) {
                console.log(data);
                $('#updateStatusLoader').hide();
                window.location.reload();
                return false;
            })
            .error(function (data, status, headers, config) {
                //this always gets called
                console.log(status);
            });
            return false;  
       }
    });
</script>