 <?php $baseUrl = $this->basePath(); ?>


<div class="container">
	<div class="margin_top12"></div>
	<div class="page-header">
  <div class="clearfix"></div>  
  <h3>Email Verification</h3></div>
<div class="container margin_top2">
<div class="content_left">  
    <div class="bs-example margin_top2">
        Your email has been verified successfully.
    </div><!-- /example -->     
</div><!-- end content left side -->
</div>
</div> 




  
  