<?php $baseUrl = $this->basePath(); ?>
﻿<!doctype html>
<html lang="en-gb" class="no-js">
<head>
	<title></title>	
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="keywords" content="" />
	<meta name="description" content="" />
    <link rel="shortcut icon" type="image/png" href="images/favicon.png"/>

	<link rel="shortcut icon" href="images/favicon.html">
    

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
   	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Dancing+Script:400,700' rel='stylesheet' type='text/css'>

	
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/reset.css" type="text/css" />
	<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/style.css" type="text/css" />
    
    <!-- font awesome icons -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/font-awesome/css/font-awesome.min.css"> 
    
    <!-- mega menu -->
    <link href="<?php echo $baseUrl;?>/public/js/mainmenu/bootstrap.min.css" rel="stylesheet">
    <script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/universal/jquery.js"></script>
	    
</head>

<body>

<div class="site_wrapper">
<div class="clearfix"></div>
<div class="page_title2" style="background-color:#333;">
<div class="container">    
    <div class="pagenation">&nbsp;</div>
     
</div>
</div><!-- end page title --> 

<div class="clearfix"></div>

<div class="content_fullwidth less2">
<div class="container">
    <div class="logregform col-md-4 col-md-offset-4" style="padding-left:0px; padding-right:0px;">     
        <div class="title">        
			<h3>Reset Password</h3>      
        </div>        
        <div class="feildcont">        	   
            <form action="" method="post" id="resetPswdForm">   
                <input type="hidden" name="userId" value="<?php echo $this->userId?>">
                <label><i class="fa fa-lock"></i> Password</label>
                <input type="password" name="pswdVal" id="pswdVal">
                <label><i class="fa fa-lock"></i> Confirm Password</label>
                <input type="password" name="confPswdVal" id="confPswdVal"> 
                <button type="button" class="fbut submitResetPswd">Reset Password</button>                    
            </form>                  
        </div>
    </div>     
</div>
</div><!-- end content area -->
</div>
</body>
</html>
<script>
    $('.submitResetPswd').click(function(){
        var pswdVal     = $('#pswdVal').val();
        var confPswdVal = $('#confPswdVal').val();
        var error = 0;
        if(pswdVal==''){
            $('#pswdVal').css('border-color','red');
            error++;;
        }else{
            $('#pswdVal').css('border-color','#ccc');
        }
        if(confPswdVal==''){
            $('#confPswdVal').css('border-color','red');
            error++;;
        }else{
            $('#confPswdVal').css('border-color','#ccc');
        }
        if(error==0 && pswdVal==confPswdVal){
            $('#resetPswdForm').submit();
        }
        
    });
</script>