<?php $baseUrl = $this->basePath(); ?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CRM | Reset Password</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/plugins/iCheck/square/blue.css">
    <script src="<?php echo $baseUrl;?>/public/angular.min.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition login-page">
    <div class="login-box">
      <div class="login-logo">
        <a href="#"><b>Discovery</b>SOLUTIONS</a>
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Reset Password for CRM Account</p>
        <form ng-app="myApp" action="#" method="post" ng-controller="validateCtrl" 
name="myForm" novalidate>
           <?php if(isset($this->successMsg) || isset($this->errorMsg)){?> 
          <div class="form-group has-feedback">  
              <?php if(isset($this->successMsg))?> 
              <span style="color:green"><?php echo $this->successMsg?></span>
              <?php if(isset($this->errorMsg))?> 
              <span style="color:red"><?php echo $this->errorMsg?></span>
          </div>  
            <?php }?>  
          <div class="form-group has-feedback">
            <input type="email" name="email" class="form-control" placeholder="Email" ng-model="email" required>
            <span style="color:red" ng-show="myForm.email.$dirty && myForm.email.$invalid">
            <span ng-show="myForm.email.$error.required">Email is required.</span>
            <span ng-show="myForm.email.$error.email">Invalid email address.</span>
            </span>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>          
          <div class="row">
            <div class="col-xs-5 col-xs-offset-3" style="padding-right:5px;">
            	<button type="submit" class="btn btn-primary btn-block btn-flat" ng-disabled="!(!!email)">Reset Password</button></div><!-- /.col -->
            <div class="col-xs-4" style="padding-left:5px;">
                <button type="button" class="btn btn-danger btn-block btn-flat" ng-click="cancel()">Cancel</button>
            </div><!-- /.col -->
          </div>
        </form>

        <!-- /.social-auth-links -->

       
        

      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->

    <!-- jQuery 2.1.4 -->
    <script src="<?php echo $baseUrl;?>/public/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="<?php echo $baseUrl;?>/public/bootstrap/js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="<?php echo $baseUrl;?>/public/plugins/iCheck/icheck.min.js"></script>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
      <script>
    var app = angular.module('myApp', []);
    app.controller('validateCtrl', function($scope) {
       // $scope.password = '';
        $scope.cancel = function(){
            window.location.href = '<?php echo $baseUrl?>/index';
        };
        
    });
</script>
  </body>
</html>
