<?php $baseUrl = $this->basePath(); ?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CRM | Reset Password</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="<?php echo $baseUrl;?>/public/plugins/iCheck/square/blue.css">
    <script src="<?php echo $baseUrl;?>/public/angular.min.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition login-page">
    <div class="login-box">
      <div class="login-logo">
        <a href="#"><b>Discovery</b>SOLUTIONS</a>
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Reset Password for CRM Account</p>
        <form ng-app="myApp" action="#" method="post" ng-controller="validateCtrl" 
name="myForm" novalidate>
          <input type="hidden" name="userId" value="<?php echo $this->userId?>">
          
          <?php if(isset($this->successMsg)){?> 
          <div class="form-group has-feedback">  
              <span style="color:green">Password changed. <a href="<?php echo $baseUrl?>/index">Click</a> here to login.</span>
          </div>  
            <?php }?>  
          <div class="form-group has-feedback">
            <input type="password" name="pswdVal" class="form-control" placeholder="New Password" ng-model="pswdVal" required>
            <span style="color:red" ng-show="myForm.pswdVal.$dirty && myForm.pswdVal.$invalid">
            <span ng-show="myForm.pswdVal.$error.required">New Password is required.</span>
            </span>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>  
          <div class="form-group has-feedback">
            <input type="password" name="confPswdVal" class="form-control" placeholder="Confirm Password" ng-model="confPswdVal" ng-blur="myfunc()" ng-match="pswdVal" required>
            <span style="color:red" ng-show="paswdMatch" >Password do not match.</span>
            <span style="color:red" ng-show="myForm.confPswdVal.$dirty && myForm.confPswdVal.$invalid">
            <span ng-show="myForm.confPswdVal.$error.required">Confirm Password is required.</span>
            </span>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-5 col-xs-offset-3" style="padding-right:5px;">
            	<button type="submit" class="btn btn-primary btn-block btn-flat" ng-disabled="(myForm.confPswdVal.$viewValue != myForm.pswdVal.$viewValue)">Reset Password</button>
            </div><!-- /.col -->
            <div class="col-xs-4" style="padding-left:5px;">
                <button type="button" class="btn btn-danger btn-block btn-flat">Cancel</button>
            </div><!-- /.col -->
          </div>
        </form>
        <!-- /.social-auth-links -->
      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->

    <!-- jQuery 2.1.4 -->
    <script src="<?php echo $baseUrl;?>/public/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="<?php echo $baseUrl;?>/public/bootstrap/js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="<?php echo $baseUrl;?>/public/plugins/iCheck/icheck.min.js"></script>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
      <script>
    var app = angular.module('myApp', []);
    app.controller('validateCtrl', function($scope) {
       // $scope.password = '';
        $scope.paswdMatch = false;
        $scope.myfunc = function(){
            $scope.paswdMatch = ($scope.pswdVal != $scope.confPswdVal) ? true : false;
        }
    });
</script>
  </body>
</html>
